typography_spectrum: 0.4189859798643738
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2777323026675731
  lightness: 0.5009907139465213
  saturation: 0.6838286118581891
  rhythmicContrast: 0.45988347427919507
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5216673200484365
analytics:
  google: null
  facebook: null
  twitter: null
name: Inkshedmedia
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2014082c-e116-4a3b-8b27-ab2c90f923ce.jpg
title: Branding + Marketing Communications
description: Think outside the cliche
purpose: []
