name: Inkshedmedia
favicon: null
layout_spectrum: 0.5216673200484365
typography_spectrum: 0.4189859798643738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2777323026675731
  lightness: 0.5009907139465213
  saturation: 0.6838286118581891
  rhythmicContrast: 0.45988347427919507
purpose: []
